# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dfbeta_stat <- function(sigma, X, y, par) {
    .Call(`_glmmr_dfbeta_stat`, sigma, X, y, par)
}

GradRobustStep <- function(N, idx_in, C_list, X_list, sig_list, weights, exp_cond, nfix, any_fix = 0L, rd_mode = 1L, trace = TRUE) {
    .Call(`_glmmr_GradRobustStep`, N, idx_in, C_list, X_list, sig_list, weights, exp_cond, nfix, any_fix, rd_mode, trace)
}

GradRobustAlg1 <- function(N, idx_in, C_list, X_list, sig_list, weights, exp_cond, nfix, any_fix = 0L, rd_mode = 1L, trace = TRUE) {
    .Call(`_glmmr_GradRobustAlg1`, N, idx_in, C_list, X_list, sig_list, weights, exp_cond, nfix, any_fix, rd_mode, trace)
}

log_factorial_approx <- function(n) {
    .Call(`_glmmr_log_factorial_approx`, n)
}

gaussian_cdf <- function(x) {
    .Call(`_glmmr_gaussian_cdf`, x)
}

gaussian_cdf_vec <- function(v) {
    .Call(`_glmmr_gaussian_cdf_vec`, v)
}

gaussian_pdf <- function(x) {
    .Call(`_glmmr_gaussian_pdf`, x)
}

gaussian_pdf_vec <- function(v) {
    .Call(`_glmmr_gaussian_pdf_vec`, v)
}

log_mv_gaussian_pdf <- function(u, D, logdetD) {
    .Call(`_glmmr_log_mv_gaussian_pdf`, u, D, logdetD)
}

log_likelihood <- function(y, mu, var_par, family, link) {
    .Call(`_glmmr_log_likelihood`, y, mu, var_par, family, link)
}

mod_inv_func <- function(mu, link) {
    .Call(`_glmmr_mod_inv_func`, mu, link)
}

gen_dhdmu <- function(xb, family, link) {
    .Call(`_glmmr_gen_dhdmu`, xb, family, link)
}

obj_fun <- function(A, U2) {
    .Call(`_glmmr_obj_fun`, A, U2)
}

c_obj_fun <- function(M, C) {
    .Call(`_glmmr_c_obj_fun`, M, C)
}

gen_m <- function(X, A) {
    .Call(`_glmmr_gen_m`, X, A)
}

fexp <- function(x, par1, par2) {
    .Call(`_glmmr_fexp`, x, par1, par2)
}

sqexp <- function(x, par1, par2) {
    .Call(`_glmmr_sqexp`, x, par1, par2)
}

matern <- function(x, rho, nu) {
    .Call(`_glmmr_matern`, x, rho, nu)
}

bessel1 <- function(x, rho) {
    .Call(`_glmmr_bessel1`, x, rho)
}

blockMat <- function(matfield) {
    .Call(`_glmmr_blockMat`, matfield)
}

genBlockD <- function(N_dim, N_func, func_def, N_var_func, col_id, N_par, cov_data, gamma) {
    .Call(`_glmmr_genBlockD`, N_dim, N_func, func_def, N_var_func, col_id, N_par, cov_data, gamma)
}

genD <- function(B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, gamma) {
    .Call(`_glmmr_genD`, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, gamma)
}

remove_one_many_mat <- function(A, i) {
    .Call(`_glmmr_remove_one_many_mat`, A, i)
}

remove_one_many <- function(A, i, u) {
    .Call(`_glmmr_remove_one_many`, A, i, u)
}

add_one <- function(A, sigma_jj, f, u) {
    .Call(`_glmmr_add_one`, A, sigma_jj, f, u)
}

add_one_mat <- function(A, sigma_jj, f) {
    .Call(`_glmmr_add_one_mat`, A, sigma_jj, f)
}

uvec_minus <- function(v, rm_idx) {
    .Call(`_glmmr_uvec_minus`, v, rm_idx)
}

sepBlockMat <- function(X) {
    .Call(`_glmmr_sepBlockMat`, X)
}

invBlockMat <- function(X) {
    .Call(`_glmmr_invBlockMat`, X)
}

logDetBlockMat <- function(X) {
    .Call(`_glmmr_logDetBlockMat`, X)
}

d_lik_optim <- function(B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, u, start, lower, upper, trace = 0L, block = TRUE) {
    .Call(`_glmmr_d_lik_optim`, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, u, start, lower, upper, trace, block)
}

l_lik_optim <- function(Z, X, y, u, family, link, start, lower, upper, trace) {
    .Call(`_glmmr_l_lik_optim`, Z, X, y, u, family, link, start, lower, upper, trace)
}

f_lik_grad <- function(B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, Z, X, y, u, cov_par_fix, family, link, start, lower, upper, tol = 1e-4, block = TRUE) {
    .Call(`_glmmr_f_lik_grad`, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, Z, X, y, u, cov_par_fix, family, link, start, lower, upper, tol, block)
}

f_lik_hess <- function(B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, Z, X, y, u, cov_par_fix, family, link, start, lower, upper, tol = 1e-4, block = TRUE) {
    .Call(`_glmmr_f_lik_hess`, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, Z, X, y, u, cov_par_fix, family, link, start, lower, upper, tol, block)
}

f_lik_optim <- function(B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, Z, X, y, u, cov_par_fix, family, link, start, lower, upper, trace, block = TRUE) {
    .Call(`_glmmr_f_lik_optim`, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, Z, X, y, u, cov_par_fix, family, link, start, lower, upper, trace, block)
}

mcnr_step <- function(y, X, Z, beta, u, family, link) {
    .Call(`_glmmr_mcnr_step`, y, X, Z, beta, u, family, link)
}

aic_mcml <- function(Z, X, y, u, family, link, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, beta_par, cov_par) {
    .Call(`_glmmr_aic_mcml`, Z, X, y, u, family, link, B, N_dim, N_func, func_def, N_var_func, col_id, N_par, sum_N_par, cov_data, beta_par, cov_par)
}

