# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obj_fun <- function(A, U2) {
    .Call(`_glmmr_obj_fun`, A, U2)
}

c_obj_fun <- function(M, C) {
    .Call(`_glmmr_c_obj_fun`, M, C)
}

gen_m <- function(X, A) {
    .Call(`_glmmr_gen_m`, X, A)
}

gen_u <- function(M, X, C) {
    .Call(`_glmmr_gen_u`, M, X, C)
}

remove_one <- function(A, i, u) {
    .Call(`_glmmr_remove_one`, A, i, u)
}

remove_one_mat <- function(A, i) {
    .Call(`_glmmr_remove_one_mat`, A, i)
}

add_one <- function(A, sigma_jj, f, u) {
    .Call(`_glmmr_add_one`, A, sigma_jj, f, u)
}

add_one_mat <- function(A, sigma_jj, f) {
    .Call(`_glmmr_add_one_mat`, A, sigma_jj, f)
}

ChooseSwap <- function(idx_in, A, sig, u, out2, out3) {
    .Call(`_glmmr_ChooseSwap`, idx_in, A, sig, u, out2, out3)
}

Grad <- function(idx_in, A, sig, u, tol = 1e-9, trace = TRUE) {
    .Call(`_glmmr_Grad`, idx_in, A, sig, u, tol, trace)
}

ChooseSwapRobust <- function(nlist, idx_in, A_list, sig_list, u_list, weights, out2, out3) {
    .Call(`_glmmr_ChooseSwapRobust`, nlist, idx_in, A_list, sig_list, u_list, weights, out2, out3)
}

GradRobust <- function(nlist, idx_in, A_list, M_list, C_list, X_list, sig_list, u_list, weights, tol = 1e-9, trace = TRUE) {
    .Call(`_glmmr_GradRobust`, nlist, idx_in, A_list, M_list, C_list, X_list, sig_list, u_list, weights, tol, trace)
}

uvec_minus <- function(v, rm_idx) {
    .Call(`_glmmr_uvec_minus`, v, rm_idx)
}

GradRobustStep <- function(idx_in, C_list, X_list, sig_list, weights, nfix = 0L, rd_mode = 1L) {
    .Call(`_glmmr_GradRobustStep`, idx_in, C_list, X_list, sig_list, weights, nfix, rd_mode)
}

GradRobustAlg1 <- function(idx_in, C_list, X_list, sig_list, weights, nfix = 0L, rd_mode = 1L) {
    .Call(`_glmmr_GradRobustAlg1`, idx_in, C_list, X_list, sig_list, weights, nfix, rd_mode)
}

findFunc <- function(funcdetail, data1, data2, pars) {
    .Call(`_glmmr_findFunc`, funcdetail, data1, data2, pars)
}

genSubD <- function(func, data, pars) {
    .Call(`_glmmr_genSubD`, func, data, pars)
}

blockMat <- function(mat1, mat2) {
    .Call(`_glmmr_blockMat`, mat1, mat2)
}

genD <- function(func, data, pars) {
    .Call(`_glmmr_genD`, func, data, pars)
}

log_factorial_approx <- function(n) {
    .Call(`_glmmr_log_factorial_approx`, n)
}

d_lik_optim <- function(func, data, u, start) {
    .Call(`_glmmr_d_lik_optim`, func, data, u, start)
}

log_likelihood <- function(y, mu, var_par, family, link) {
    .Call(`_glmmr_log_likelihood`, y, mu, var_par, family, link)
}

l_lik_optim <- function(Z, X, y, u, family, link, start) {
    .Call(`_glmmr_l_lik_optim`, Z, X, y, u, family, link, start)
}

f_lik_optim <- function(func, data, Z, X, y, u, cov_par_fix, family, link, start, lower, importance) {
    .Call(`_glmmr_f_lik_optim`, func, data, Z, X, y, u, cov_par_fix, family, link, start, lower, importance)
}

inv_func <- function(mu, link) {
    .Call(`_glmmr_inv_func`, mu, link)
}

mod_inv_func <- function(mu, link) {
    .Call(`_glmmr_mod_inv_func`, mu, link)
}

mcnr_step <- function(y, X, Z, beta, u, link) {
    .Call(`_glmmr_mcnr_step`, y, X, Z, beta, u, link)
}

